client localhost {
	ipaddr = 127.0.0.1
	secret = testing123
	require_message_authenticator = no
	nas_type = other
}

client netgrid_network {
	ipaddr = 172.28.0.0/16
	secret = netgrid_radius_secret
	require_message_authenticator = no
	nas_type = other
}
